public:
  libraries:
    - name: Zefiros-Software/GoogleTest
      version: '@head || ^1.0.0'
    - name: Zefiros-Software/GoogleBenchmark
      version: '@head'
settings:
  installCI:
    default: false
    reduce: allTrue