platform:
  - x64
build: off
environment:
  PYTHON: "C:\\Python35"
  PROJECT: {{PROJECT_NAME}}
  PROJECT_DIRECTORY: {{PROJECT_DIRECTORY}}
  matrix:  
    - TYPE: zpm
    - BUILD_CONFIG: release
      BUILD_ARCHITECTURE: x86
    - BUILD_CONFIG: debug
      BUILD_ARCHITECTURE: x86
    - BUILD_CONFIG: release
      BUILD_ARCHITECTURE: x86_64
    - BUILD_CONFIG: debug
      BUILD_ARCHITECTURE: x86_64
    - BUILD_CONFIG: release
      BUILD_ARCHITECTURE: x86_64
    - BUILD_CONFIG: release 
      BUILD_ARCHITECTURE: x86_64
install:
  - powershell -command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.bat -OutFile %TEMP%/install-zpm.bat;" && %TEMP%/install-zpm.bat 
  - "SET PATH=%PATH%;%USERPROFILE%/zpm/bin"
test_script:
  - zpm run build-ci-library
deploy_script:
  - zpm run deploy-ci-library 
